### ISSUE TITLE
"statusMessage": "Failed plugins:\n/Tsunami Team (tsunami-dev@google.com)/VULN_DETECTION/NcrackWeakCredentialDetectorPlugin/0.1"

### ISSUE THREAD

**Issue by openkasnet** [google/tsunami-security-scanner-plugins#1]
Hi.
When using this program, it gives you a message
![ksnip_20200621-223816](https://user-images.githubusercontent.com/3051932/85231391-f4a22e80-b40f-11ea-9a70-6f2c1554a4c2.png)

""status Message": "Failed plugins:\n/Tsunami Team (tsunami-dev@google.com)/VULN_DETECTION/NcrackWeakCredentialDetectorPlugin/0.1"

**Comment by magl0** [comment]
Hi, thanks for reporting this issue!

Can you please upload the full execution log of the scan and let us know the version of `ncrack` you are using?

```
ncrack -V
```

**Comment by gr-okamoto** [comment]
Hello.
I got same message.

I ran quick_start.sh and it have been finished successfully. Also, ncrack itself seems to run perfectly without any issue.

My setup is as follows.

> CentOS Linux release 7.7.1908 (Core)
> 3.10.0-1062.4.1.el7.x86_64

`$ ncrack -V

Ncrack version 0.7 ( http://ncrack.org )
Modules: SSH, RDP, FTP, Telnet, HTTP(S), Wordpress, POP3(S), IMAP, CVS, SMB, VNC, SIP, Redis, PostgreSQL, MQTT, MySQL, MSSQL, MongoDB, Cassandra, WinRM, OWA, DICOM`

I attached my full execution log as well.

[fullexecutionlog.txt](https://github.com/google/tsunami-security-scanner-plugins/files/4830955/fullexecutionlog.txt)

**Comment by openkasnet** [comment]
> ncrack

I didn't have ncrack installed.
Made apt install ncrack
Turn out,
Thank you for your work

![ksnip_20200625-205354](https://user-images.githubusercontent.com/3051932/85753829-06dcdf00-b726-11ea-9890-58ca7034f9dc.png)

**Comment by GuilleBazzi** [comment]
I'm having the same issue plus WordPressInstallPageDetector.
I don't even found anything Googling the issue
This is my console output:
![image](https://user-images.githubusercontent.com/22010821/86997248-0449a300-c184-11ea-896a-703c48a5bda1.png)
