### ISSUE TITLE
Dirname error in govtech build_all.sh

### ISSUE THREAD

**Issue by engn33r** [google/tsunami-security-scanner-plugins#12]
@GovTech-CSG I am attempting to run the build_all.sh script from within the /tsunami-security-scanner-plugins/govtech directory using "./build_all.sh" (as described in the README) and am getting the following error:

`dirname: missing operand
Try 'dirname --help' for more information.`

While I have not used dirname much, I would guess the issue is with the 2nd instance of dirname, on line 24, since dirname appears to lack an argument there https://github.com/google/tsunami-security-scanner-plugins/blob/1fdb5fe91c19091f1b3d69708f21f9be5b9f584d/govtech/build_all.sh#L24

Let me know if I'm missing something. I have dirname v8.30 on an updated Ubuntu install, in case this is a dirname version issue.

**Comment by engn33r** [comment]
On closer inspection, my best guess for the root cause of the error message is a missing `gradlew` file under /tsunami-security-scanner-plugins/govtech/detectors/cves/cve_2020_3452. Such a file exists for the google plugins, but is absent here. When no file is found, no argument is provided to the dirname utility.

**Comment by magl0** [comment]
This should be fixed by commit 16a4bd78b6aa2788e613c732662140c352fea52f.
