### ISSUE TITLE
PRP: Request Web Application Fingerprint - Elasticsearch & Kibana

### ISSUE THREAD

**Issue by C4o** [google/tsunami-security-scanner-plugins#134]
Hi there,

I would like to start the implementation for a web application fingerprint that detects the following software - Elasticsearch and Kibana

Docker hub image: 
https://hub.docker.com/_/elasticsearch
https://hub.docker.com/_/kibana

Please let me know if this is in scope.

**Comment by maoning** [comment]
Hi @C4o ,

Thanks for your request! This vulnerability is in scope for the reward program. Please submit our [participation form](https://docs.google.com/forms/d/1SH8gyUnaGY3ezXY864oEuDZoOxrE5gJHYkcoiB_bu8I) and you can start working on the development.

Please keep in mind that the Tsunami Scanner Team will only be able to work at one issue at a time for each participant so please hold on the implementation work for any other requests you might have.

Thanks!

**Comment by C4o** [comment]
Hi @maoning, 
I wonder that if I provide its fingerprint, do I need to provide the fingerprint of the full version and subsequent new versions?

**Comment by maoning** [comment]
Hi @C4o , please provide finger prints for at least the versions from the last 3-5 years, and also include an automation script that will update the prebuilt fingerprint database when there is a new release of the web application (this will cover subsequent new versions).  I realized that we currently don't have an automation script as an example, I will see if I can add one asap. 

It is hard to gauge the relevancy of pending detector requests without the fingerprinters to identify how often tsunami scanner encounters these software in the wild. I have already approved a confluence fingerprinting request https://github.com/google/tsunami-security-scanner-plugins/issues/64, once it is rolled out, it will help to measure how relevant #223 is.

**Comment by C4o** [comment]
Hi @maoning , 

I think it may be difficult to automatically update the fingerprint of the new version, cause it's hard to know what code is added in the new version and what features are caused by an automation script:(

Are there any feasible methods for reference? I'll try it.

**Comment by C4o** [comment]
Copy that. Thanks.

**Comment by tooryx** [comment]
Also @C4o, I see that this request has been opened for quite some time. Are you still willing to contribute to this plugin or should I just close it out?

**Comment by C4o** [comment]
@tooryx Yes, I'll try to contribute to this plugin recently.

**Comment by C4o** [comment]
Hi @tooryx.

It seems that elasticsearch and kibana cannot be fingerprinted by this way cause all static files cannot be requested directly. So I think this issue should be closed.

And BTW, I tested other fingerprinter plugins, including wordpress/drupal/zabbix, I found errors occurred with no correct version when there are empty lines in versions.txt, and It worked after I delete the last line.
```
......
Fingerprint updated successfully
drupal_7.74
Fingerprinting Drupal version  ...
docker: invalid reference format.
See 'docker run --help'.
```

**Comment by tooryx** [comment]
Could you at least proceed with submitting the Kibana ones for now? We can look again in Kibana when I have more time.

_~tooryx_

**Comment by C4o** [comment]
@tooryx, yes of course, I'm working on fingerprinter with kibana in the past few days.

**Comment by tooryx** [comment]
Hi @C4o,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!

**Comment by tooryx** [comment]
Hi @C4o,

Could you please fill the new [participation form](https://bughunters.google.com/report/tsunami)?

Thank you,
~tooryx

**Comment by C4o** [comment]
Hi @tooryx, l've submitted a new form.
