### ISSUE TITLE
Feature request: Support for passing cli args to nmap

### ISSUE THREAD

**Issue by gaby** [google/tsunami-security-scanner-plugins#18]
I have been playing with tsunami, and I noticed the configuration files for the nmap scanner only support the path of the binary and list of ports. 

Is there any way of passing additional arguments to the nmap binary, like the ones you would used in a cli ?

**Comment by erikvarga** [comment]
Right now we don't have a way of passing more arguments to nmap than from the port ranges+protocols and the root paths. Do you have a use case in mind where nmap would benefit from receiving additional arguments?

**Comment by gaby** [comment]
@erikvarga When running tsunami against my remote services running in k8s the nmap scan takes 5-6 hours. The reason is because the default nmap config is trying to scan almost every port instead of common ports.

Ideally I would prefer to be able to use ```--top-ports 1000``` when calling nmap.

From the docs:

> The –top-ports option lets you specify the number of ports you wish to scan in each protocol, and will pick the most popular ports for you based on the new frequency data. For both TCP and UDP, the top 10 ports gets you roughly half of the open ports. The top 1,000 (out of 65,536 possible) finds roughly 93% of the open TCP ports and more than 95% of the open UDP ports.


More info here: https://danielmiessler.com/blog/nmap-use-the-top-ports-option-for-both-tcp-and-udp-simultaneously/

**Comment by erikvarga** [comment]
Right, customizing the CLI args Nmap runs on sounds like something we should add to Tsunami in the long term. Of course we're always happy to accept contributions on this from external people too.

For your specific issue, Nmap should already default to the top 1000 ports if no other options are specified, according to https://nmap.org/book/performance-port-selection.html , so it sounds like your slowness might be coming from somewhere else.
You could try manually adding the a smaller number of ports (such as the 100 ports) to the tsunami config file and see if that speeds things up.

**Comment by gaby** [comment]
Thanks! I will try running it with Top 100 ports, to see if run time improves!

**Comment by gaby** [comment]
@erikvarga Passing the top-100 ports solved the problem :-)
