### ISSUE TITLE
PRQ: Request Web Application Fingerprint - Zabbix

### ISSUE THREAD

**Issue by hh-hunter** [google/tsunami-security-scanner-plugins#236]
Hello.

I would like to start implement a tsunami fingerprint for Zabbix,Please let me know if this is in scope to start with its development.

**Comment by maoning** [comment]
Hi @hh-hunter,

Thanks for your request! This web application fingerprint is in scope for the reward program. Please submit our [participation form](https://docs.google.com/forms/d/1SH8gyUnaGY3ezXY864oEuDZoOxrE5gJHYkcoiB_bu8I) and you can start working on the development.

Please keep in mind that the Tsunami Scanner Team will only be able to work at one issue at a time for each participant so please hold on the implementation work for any other requests you might have.

Thanks!
