### ISSUE TITLE
PRP: Update Adminer Fingerprint

### ISSUE THREAD

**Issue by fmunozs** [google/tsunami-security-scanner-plugins#274]
hello,

I'd like to work on updating the fingerprint for Adminer, the current fingerprint only detects up to 4.7.8 and there are some new versions (4.8.1, 4.8.0, 4.7.9)

I will provide an script to automatically generate the fingerprint from 4.2.5 to 4.8.1 

Thanks!

**Comment by maoning** [comment]
Hi @[username_of_the_requester],

Thanks for your request! This fingerprint is in scope for the reward program. Please submit our [participation form](https://docs.google.com/forms/d/1SH8gyUnaGY3ezXY864oEuDZoOxrE5gJHYkcoiB_bu8I) and you can start working on the development.

Please keep in mind that the Tsunami Scanner Team will only be able to work at one issue at a time for each participant so please hold on the implementation work for any other requests you might have.

Thanks!

**Comment by maoning** [comment]
Hi @fmunozs, thank you for the contribution, the reward has been granted, and you should be notified later today or tomorrow.
