### ISSUE TITLE
PRP: Datahub Fingerprint Database and update script

### ISSUE THREAD

**Issue by timoles** [google/tsunami-security-scanner-plugins#289]
Hi tsunami team,

I would like to start implement a fingerprint for [Datahub](https://github.com/datahub-project/datahub), including the update script, as stated within [this issue](https://github.com/google/tsunami-security-scanner-plugins/issues/287).

I'm planing to do a fingerprint for each `v.x.x` tag available within Dockerhub. For example: https://hub.docker.com/r/linkedin/datahub-ingestion/tags?page=1&name=0.8

**Comment by maoning** [comment]
Hi @timoles ,

Thanks for your request! This fingerprint is in scope for the reward program. Please submit our [participation form](https://docs.google.com/forms/d/1SH8gyUnaGY3ezXY864oEuDZoOxrE5gJHYkcoiB_bu8I) and you can start working on the development.

Currently we are still in progress of ironing out the fingerprint submission process, I'm hoping to merge in zabbix fingerprint changes https://github.com/google/tsunami-security-scanner-plugins/pull/272 asap to set up the community fingerprint locations.  

Please keep in mind that the Tsunami Scanner Team will only be able to work at one issue at a time for each participant so please hold on the implementation work for any other requests you might have.

Thanks!

**Comment by maoning** [comment]
Hi @timoles, 2 of the community-contributed fingerprints has been merged. I've added some instructions at https://github.com/google/tsunami-security-scanner-plugins/tree/master/google/fingerprinters/web. It is probably not fully comprehensive, if you see any gaps in the documentation, feel free to update the README.md with more details.

**Comment by timoles** [comment]
Hi everyone. The Datahub are done and waiting for a PR review for some time. Could you please check if everything is good to go?
Thanks!

**Comment by tooryx** [comment]
Hi @timoles,

I have labeled your other issues as "Contributor queue" for now. We are enforcing more strictly the one review per contributor as we cannot keep up with review otherwise. We will review this plugin and then dequeue the other ones progressively.

If you think I incorrectly labeled one of the issues, please let me know.
~tooryx

**Comment by tooryx** [comment]
Hi @timoles,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!

**Comment by tooryx** [comment]
Hi @timoles,

The panel has decided on a reward. You should receive a message from the bughunter platform soon.
Let me know if there are any issue.

~tooryx
