### ISSUE TITLE
PRP: Prometheus fingerprint db and update scripts

### ISSUE THREAD

**Issue by fmunozs** [google/tsunami-security-scanner-plugins#295]
Hello team, 

I'd like to work on a script to generate Prometheus fingerprint automatically. The fingerprinter will detect Prometheus 1.0 to 2.43.0

Prometheus is a free software application used for event monitoring and alerting.

https://prometheus.io/

Thank you

**Comment by maoning** [comment]
Hi @fmunozs,

Thanks for your request! This vulnerability is in scope for the reward program. Please submit our [participation form](https://docs.google.com/forms/d/1SH8gyUnaGY3ezXY864oEuDZoOxrE5gJHYkcoiB_bu8I) and you can start working on the development.

Please keep in mind that the Tsunami Scanner Team will only be able to work at one issue at a time for each participant so please hold on the implementation work for any other requests you might have.

Thanks!

**Comment by fmunozs** [comment]
@maoning sorry to bother, is there any update on this https://github.com/google/tsunami-security-scanner-plugins/pull/300 ? Thank you!

**Comment by fmunozs** [comment]
@maoning @tooryx hey! I see that this issue was recently assigned to me, is there anything on my side that should be done? Thanks

**Comment by tooryx** [comment]
Hi @fmunozs,

Could you also please fill in [the new participation form](https://bughunters.google.com/report/tsunami)?

Thank you,
_~tooryx_

**Comment by fmunozs** [comment]
@tooryx I have just completed the participation form! thank you

**Comment by tooryx** [comment]
Hi @fmunozs,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!

**Comment by tooryx** [comment]
Hi @fmunozs,

The reward has been granted. You will receive very soon a message about it on the ticket you opened.

_~tooryx_
