### ISSUE TITLE
fingerprinters plugin - isIgnoredLocalFile ignores files without extensions

### ISSUE THREAD

**Issue by fmunozs** [google/tsunami-security-scanner-plugins#297]
While implementing a new fingerprint I was attempting to get it to use some files and the plugin did not catch them. 

After reviewing the plugin source I noticed that in this method **FingerprintUpdater.java::isIgnoredLocalFile** claims that it will skip over hidden files or folders, but it also skips files without extensions.

```
  private static boolean isIgnoredLocalFile(String relativePath) {
    // Use the relative path so that parent directory names are not checked.
    String extension = Files.getFileExtension(Ascii.toLowerCase(relativePath));
    // Ignores hidden files and folders.
    if (extension.isEmpty() || relativePath.startsWith(".") || relativePath.contains("/.")) {
      return true;
    }
```

https://github.com/google/tsunami-security-scanner-plugins/blob/master/google/fingerprinters/web/src/main/java/com/google/tsunami/plugins/fingerprinters/web/tools/FingerprintUpdater.java#L291

I am not sure about why this was added. In the application I am working, there are several files without extension that will improve the fingerprinting.

**Comment by maoning** [comment]
@fmunozs, could you make the files without extension a configurable parameter in FingerprintUpdater? The main concern is that this may make other generated fingerprints unstable.

**Comment by fmunozs** [comment]
@maoning hello ! I am working on this but I have one additional question: Is it Ok if I also update the common.sh **updateFingerprint** function to allow as an optional parameter the use of extensionless files while executing the fingerprint? it shouldnt affect other scripts as I will not require that parameter and by default it will be false.
