### ISSUE TITLE
PRP: Drupal fingerprint db and update scripts

### ISSUE THREAD

**Issue by c0nsultant33** [google/tsunami-security-scanner-plugins#305]
Hello team,

I'd like to work on a script to generate Drupal fingerprints automatically. The fingerprinter will detect Drupal versions:

1. 9.0.7
2. 9.0.8
3. 9.0.9
4. 9.1.0
5. 9.1.10
6. 9.1.11
7. 9.1.12
8. 9.1.13
9. 9.1.14
10. 9.1.15
11. 9.1.2
12. 9.1.3
13. 9.1.4
14. 9.1.5
15. 9.1.6
16. 9.1.7
17. 9.1.8
18. 9.1.9
19. 9.2.0
20. 9.2.1
21. 9.2.10
22. 9.2.11
23. 9.2.12
24. 9.2.13
25. 9.2.14
26. 9.2.15
27. 9.2.16
28. 9.2.17
29. 9.2.18
30. 9.2.19
31. 9.2.2
32. 9.2.20
33. 9.2.21
34. 9.2.3
35. 9.2.4
36. 9.2.5
37. 9.2.6
38. 9.2.7
39. 9.2.8
40. 9.2.9
41. 9.3.0
42. 9.3.11
43. 9.3.12
44. 9.3.13
45. 9.3.14
46. 9.3.15
47. 9.3.16
48. 9.3.17
49. 9.3.18
50. 9.3.19
51. 9.3.2
52. 9.3.20
53. 9.3.21
54. 9.3.22
55. 9.3.3
56. 9.3.5
57. 9.3.6
58. 9.3.7
59. 9.3.8
60. 9.3.9
61. 9.4.1
62. 9.4.10
63. 9.4.11
64. 9.4.12
65. 9.4.13
66. 9.4.2
67. 9.4.3
68. 9.4.4
69. 9.4.5
70. 9.4.6
71. 9.4.7
72. 9.4.8
73. 9.4.9
74. 9.5.0
75. 9.5.1
76. 9.5.2
77. 9.5.3
78. 9.5.4
79. 9.5.5
80. 9.5.7
81. 10.0.0
82. 10.0.1
83. 10.0.2
84. 10.0.3
85. 10.0.4
86. 10.0.5
87. 10.0.7

which are missed in `**/drupal.binproto`(future versions could be fingerprinted by extending the `versions.txt` list).

**Comment by maoning** [comment]
Hi @c0nsultant33 ,

Thanks for your request! This fingerprint is in scope for the reward program. Please submit our [participation form](https://docs.google.com/forms/d/1SH8gyUnaGY3ezXY864oEuDZoOxrE5gJHYkcoiB_bu8I) and you can start working on the development.

Please keep in mind that the Tsunami Scanner Team will only be able to work at one issue at a time for each participant so please hold on the implementation work for any other requests you might have.

Thanks!

**Comment by YuriyPobezhymov** [comment]
@maoning, any updates?

**Comment by YuriyPobezhymov** [comment]
@c0nsultant33, thank you much for good words and support!
@maoning, please approve 😉!

**Comment by YuriyPobezhymov** [comment]
@maoning, any progress here?

**Comment by tooryx** [comment]
Hi @YuriyPobezhymov,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Also, I understand that you already filled the form for this issue. But we are making changes to the submission process  so I will probably need to come back to you in a few days to fill a different one. Apologies for this. I will try to make this as smooth as possible for you.

Thanks!

**Comment by tooryx** [comment]
Hi @YuriyPobezhymov,

Could you please follow the [new process](https://bughunters.google.com/report/tsunami) so that we can proceed with payment?

_~tooryx_

**Comment by YuriyPobezhymov** [comment]
Hello @tooryx!
I made submittion through new form.

**Comment by tooryx** [comment]
Thank you @YuriyPobezhymov. The panel has reached a decision and you should be soon contacted via e-mail for the next steps. Feel free to let me know if anything goes wrong in the process.
