### ISSUE TITLE
Some suggestions about the Tsunami plugin acceptance process 

### ISSUE THREAD

**Issue by am0o0** [google/tsunami-security-scanner-plugins#327]
Hi, I don't want to complain about the process and the average amount of time of receiving bounty because recently you explain the challenges before in [another ](https://github.com/google/tsunami-security-scanner-plugins/issues/281) issue.

I'm very curious about the following questions in my head:
1. why don't have a pre-pull request checklist to make your internal code review faster, e.g. you can indicate the camelCase, documentation comments for methods, and the reason for why sending such HTTP/web-socket requests, how to setup vulnerable/non-vulnerable instances of the product/application ...
2. I contributed to the codeql bug bounty program recently and they have an experimental directory even after the queries has reviewed, they keep our codeql queries and they'll make queries non-experiential after a while or more assessments and after some other internal reviews. so I think its better to here we have such a procedure because its good to we have a balance here which means plugins after a little assessment can have good and stable behavior to be experimental and then contributors can receive their bounties much earlier than before.
3. I think contributors are ready to answer your questions about the logic behind some lines of their code and I think it is good to ask them more during the internal code review process to speed up the process.

I hope I didn't make any offense to Tsunami team :)

I also want to hear the opinions of other contributors: @h0ng10 @hh-hunter  @fmunozs @timoles @shpei1963 @SuperX-SIR @mr-mosi @secureness @c0nsultant33 , ...

**Comment by mr-mosi** [comment]
Hi, 
I agree very much with 1 and 3. we need to speed up the process. curious to hear others opinion.

**Comment by secureness** [comment]
I think I'm in the same page which the experimental directory is a good idea, many users of Tsunami which are using plugins can run emergent CVEs ASAP, it is definitly better that they wait few months and then they run a higher quality plugins.can get experimental plugins result, in these results they can see that experimental phase

**Comment by secureness** [comment]
I forgot to say that with running experimental Plugins by Tsunami users, you can see user issues about errors that were missed by initial code reviews. it is great as you know the Plugin error that you could find by putting more time into code reviews.

**Comment by maoning** [comment]
Thanks all for the great feedbacks. 

For 1), we are in the process of adding an automated linter check at the start of the review process, hopefully that would remove lots of back & forth.

For 2), it's a good idea, I will circle back with my team on if we can quickly pilot the experimental plugins out :) 

We are also working on expanding the PRP review panel, though it takes time to get all the legal approvals to do so. We are hoping that we will be able to add a few more reviewers by the end of this year to fully scale up the review effort. Currently we are testing out our internal review playbook, making sure all the key steps are well documented. 

Sorry for the on-going delay, this is definitely something we want to address this year.
