### ISSUE TITLE
PRP: Weak Credential Tester for Grafana

### ISSUE THREAD

**Issue by AlessandroCotto** [google/tsunami-security-scanner-plugins#348]
Hello team,

I'm working on the Grafana weak credential detector. It'll be a CredentialTester in the "Generic Weak Credetial detector" plugin.

**Comment by maoning** [comment]
Hi @AlessandroCotto,

Thanks for your request! This vulnerability is in scope for the reward program. Please submit our [participation form](https://docs.google.com/forms/d/1SH8gyUnaGY3ezXY864oEuDZoOxrE5gJHYkcoiB_bu8I) and you can start working on the development.

Please keep in mind that the Tsunami Scanner Team will only be able to work at one issue at a time for each participant so please hold on the implementation work for any other requests you might have.

Thanks!
