### ISSUE TITLE
About Drupal fingerprints PR

### ISSUE THREAD

**Issue by YuriyPobezhymov** [google/tsunami-security-scanner-plugins#355]
Hello.
I found activisation on the repository issues, that's why I want you to ask about my frozen [PR](https://github.com/google/tsunami-security-scanner-plugins/pull/326).
I made fingerprints long time ago, but they still not merged.
I don't understand the reason. I want to move forward with some others plugins/fingerprints.

Thanks, Yuriy.

**Comment by tooryx** [comment]
I am closing this bug as recent work is tracked in #305

Feel free to yell if you disagree,
_~tooryx_
