### ISSUE TITLE
PRP: RabbitMQ Weak Credentials 

### ISSUE THREAD

**Issue by leonardo-doyensec** [google/tsunami-security-scanner-plugins#359]
Hi Tsunami Team,
I'd like to contribute a plugin for "Weak Credentials in RabbitMQ Management Portal".

The plugin detects a RabbitMQ Management Portal and attempts to detect if exists any user with weak credentials

Regards,
Leonardo Giovannini

**Comment by tooryx** [comment]
Hi @leonardo-doyensec,

Thanks for your request! This vulnerability is in scope for the reward program. Please submit our [participation form](https://bughunters.google.com/report/tsunami) and you can start working on the development.

Please keep in mind that the Tsunami Scanner Team will only be able to work at one issue at a time for each participant so please hold on the implementation work for any other requests you might have.

Thanks!

**Comment by tooryx** [comment]
Hi @leonardo-doyensec,

You should have received a message about the bounty.
Feel free to ping me if there are any issue in the process.

_~tooryx_
