### ISSUE TITLE
PRP: Request Web Application Fingerprint - Apache Solr

### ISSUE THREAD

**Issue by W0ngL1** [google/tsunami-security-scanner-plugins#395]
Hi there,

I would like to start the implementation for a web application fingerprint that detects the following software - Apache Solr.

Docker hub image:
https://hub.docker.com/_/solr

I cannot find these fingerprints in this repository. So please let me know if this is in scope.

**Comment by tooryx** [comment]
Hi @W0ngL1,

Could you please split this into two different issues? Also, can you create one for Apache Ofbiz?
Finally, let us know which one you would be interested to start with and we will tell you if you can proceed.

_~tooryx_

**Comment by tooryx** [comment]
Hi @W0ngL1,

Thanks for your request! This vulnerability is in scope for the reward program. Please submit our [participation form](https://bughunters.google.com/report/tsunami) and you can start working on the development.

Please keep in mind that the Tsunami Scanner Team will only be able to work at one issue at a time for each participant so please hold on the implementation work for any other requests you might have.

Thanks!

**Comment by tooryx** [comment]
Hi @W0ngL1,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!
