### ISSUE TITLE
PRP: Request Web Application Fingerprint - Apache Couchdb

### ISSUE THREAD

**Issue by W0ngL1** [google/tsunami-security-scanner-plugins#397]
Hi there,

I would like to start the implementation for a web application fingerprint that detects the following software - Apache Couchdb.

Docker hub image:
https://hub.docker.com/_/couchdb

I cannot find these fingerprints in this repository. So please let me know if this is in scope.

**Comment by tooryx** [comment]
Hi @W0ngL1,

You can start working on this fingerprints.

_~tooryx_

**Comment by tooryx** [comment]
Hi @W0ngL1,

I do not have a lot of experience with CouchDB, but it does not seem to really be a web service but rather a database with an HTTP-like API. Maybe it does not make sense to add a fingerprint for it in the WebFingerprinter then, what do you think?

_~tooryx_
