### ISSUE TITLE
AI PRP: Request New Web Fingerprint for Gradio

### ISSUE THREAD

**Issue by maoning** [google/tsunami-security-scanner-plugins#411]
Add a web fingerprint and updater script for [Gradio](https://github.com/gradio-app/gradio)

Please read the rules of engagement first at https://github.com/google/tsunami-security-scanner-plugins/issues/409.

**Comment by inkz** [comment]
@maoning since I worked on Gradio's CVE I would like to take this one as well

**Comment by inkz** [comment]
@maoning @vsutedjo My previous PR is merged https://github.com/google/tsunami-security-scanner-plugins/pull/446, can I take this one now?

**Comment by maoning** [comment]
Yes @inkz.

Please submit our [participation form](https://bughunters.google.com/report/tsunami) and you can start working on the development.

**Comment by inkz** [comment]
Thank you!

**Comment by tooryx** [comment]
Hi @inkz,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!

**Comment by tooryx** [comment]
Hi @inkz,

You should receive the reward message soon.

_~tooryx_

**Comment by inkz** [comment]
@tooryx thanks!
