### ISSUE TITLE
AI PRP: Request Airflow Exposed UI

### ISSUE THREAD

**Issue by maoning** [google/tsunami-security-scanner-plugins#413]
[https://github.com/projectdiscovery/nuclei-templates/blob/b686b1aea279093c30b35486db65a0e9917b66c4/http/misconfiguration/airflow/unauthenticated-airflow.yaml#L4](https://www.google.com/url?q=https://github.com/projectdiscovery/nuclei-templates/blob/b686b1aea279093c30b35486db65a0e9917b66c4/http/misconfiguration/airflow/unauthenticated-airflow.yaml%23L4&sa=D&source=buganizer&usg=AOvVaw3Z_pPbEathWpdI79ZAjzE2)

Please use callback server to verify the exposure, instead of the simple html response regex matching in the nuclei template.

Please read the rules of engagement first at https://github.com/google/tsunami-security-scanner-plugins/issues/409.

**Comment by maoning** [comment]
Hi @am0o0 ,

Thank you for picking up this request! Please make sure the following items are completed before the plugin implementation:

- [ ] Conduct vulnerability research with a brief description of how the plugin would work
- [ ] Submit the vulnerable configuration of the target application to [google/security-testbeds](https://github.com/google/security-testbeds).

I've assigned this airflow plugin to you, as this one seems to be more straightforward than #429. Once you complete this one, please remind me to assign the other one to you.

**Comment by maoning** [comment]
@am0o0 sounds good, please submit our [participation form](https://bughunters.google.com/report/tsunami) and you can start working on the testbed and plugin development.

**Comment by tooryx** [comment]
Hi @am0o0,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!

**Comment by tooryx** [comment]
Hi @am0o0,

This plugin is still in internal QC. You will receive more information once this is over (it usually last around 2 weeks, so it should be very soon).

_~tooryx_

**Comment by tooryx** [comment]
Thanks for letting me know. I will consider updating it.

_~tooryx_

**Comment by tooryx** [comment]
Hi @am0o0,

You should receive the reward message soon.

_~tooryx_
