### ISSUE TITLE
AI PRP: Request New Web Fingerprint for MLflow

### ISSUE THREAD

**Issue by maoning** [google/tsunami-security-scanner-plugins#414]
Add a web fingerprint and updater script for [MLflow](https://github.com/mlflow/mlflow).

Please read the rules of engagement first at https://github.com/google/tsunami-security-scanner-plugins/issues/409.

**Comment by maoning** [comment]
Hi @frkngksl ,

Thanks for picking up this request! Please submit our [participation form](https://bughunters.google.com/report/tsunami) and you can start working on the development.

Thanks!

**Comment by frkngksl** [comment]
Hi @maoning, I guess this issue is merged to the master branch just fyi.

**Comment by maoning** [comment]
The reward has been granted, thank you for the contribution.
