### ISSUE TITLE
AI PRP: Request New Web Fingerprint for Kubeflow Model UI

### ISSUE THREAD

**Issue by maoning** [google/tsunami-security-scanner-plugins#422]
Add a web fingerprint and updater script for [KubeFlow UI](https://www.kubeflow.org/docs/external-add-ons/kserve/webapp/).

Please read the rules of engagement first at https://github.com/google/tsunami-security-scanner-plugins/issues/409.

**Comment by shaikhyaser** [comment]
Hi @maoning, Can I contribute?

**Comment by maoning** [comment]
@shaikhyaser Please submit our [participation form](https://bughunters.google.com/report/tsunami) and you can start working on the development.

**Comment by maoning** [comment]
@shaikhyaser any update on this fingerprint? If not, I will release it back to the pool.

**Comment by hayageek** [comment]
@maoning Let me know, whether I can work on this ?

**Comment by maoning** [comment]
@hayageek Please submit our [participation form](https://bughunters.google.com/report/tsunami) and you can start working on the development.

**Comment by hayageek** [comment]
@maoning, I have submitted the participation form. I will start the work, after getting confirmation.

**Comment by hayageek** [comment]
I have completed the changes, will submit the PR in couple of days

**Comment by hayageek** [comment]
Hi @maoning ,
here is the PR: https://github.com/google/tsunami-security-scanner-plugins/pull/488

**Comment by hayageek** [comment]
@maoning  Could you please provide an update? It's been two weeks.

**Comment by tooryx** [comment]
Hi @hayageek,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!

**Comment by hayageek** [comment]
Thank you @tooryx

**Comment by tooryx** [comment]
Hi @hayageek,

We just updated the bug and you should receive information on the payment soon.

_~tooryx_

**Comment by hayageek** [comment]
Hi @tooryx , It has been 45 days, and I haven't received the payment.

**Comment by tooryx** [comment]
Hi @hayageek,

Please send an email directly to p2p-vrp@google.com, they should be able to help you efficiently.

_~tooryx_
