### ISSUE TITLE
AI PRP: Request New Web Fingerprint for Ray

### ISSUE THREAD

**Issue by maoning** [google/tsunami-security-scanner-plugins#432]
Add a web fingerprint and updater script for [Ray](https://github.com/ray-project/ray).

Please read the rules of engagement first at https://github.com/google/tsunami-security-scanner-plugins/issues/409.

**Comment by mr-mosi** [comment]
Hi, I would like to staring writing this script. thanks!

**Comment by maoning** [comment]
Hi @mr-mosi,

Please submit our [participation form](https://bughunters.google.com/report/tsunami) and you can start working on the development.

Please keep in mind that the Tsunami Scanner Team will only be able to work at one issue at a time for each participant so please hold on the implementation work for any other requests you might have.

Thanks!

**Comment by maoning** [comment]
Hi @mr-mosi ,

Your PR has been merged. This usually means a reward will be granted. Google will start the internal QC process and the reward amount will be determined based on the quality of the detector report. Please be patient and allow up to a week for the QC process to finish. You'll be notified once the decision is made.

Thanks!

**Comment by mr-mosi** [comment]
Hi @maoning ,
Thanks! I will be patient :)

**Comment by maoning** [comment]
@mr-mosi Thank you for the contribution, the reward has been granted.
