### ISSUE TITLE
PRP: Exposed Docker daemon Remote Access

### ISSUE THREAD

**Issue by am0o0** [google/tsunami-security-scanner-plugins#480]
as we have in documentation docker daemon can be exposed by a network IP address too.
please refer to https://docs.docker.com/config/daemon/remote-access/
> By default, the Docker daemon listens for connections on a Unix socket to accept requests from local clients. It's possible to allow Docker to accept requests from remote hosts by configuring it to listen on an IP address and port as well as the Unix socket. For more detailed information on this configuration option, refer to the [dockerd CLI reference](https://docs.docker.com/reference/cli/dockerd/#bind-docker-to-another-hostport-or-a-unix-socket).

**Comment by tooryx** [comment]
Thank you @am0o0 for willing to contribute.
It seems like we already have a detector for this: https://github.com/google/tsunami-security-scanner-plugins/tree/master/google/detectors/exposedui/docker

Feel free to reopen an issue if you think I was mistaken.

_~tooryx_

**Comment by tooryx** [comment]
I will discuss it with the rest of the devteam.

**Comment by tooryx** [comment]
Hi @am0o0,

I discussed this with the rest of the devteam. If it would indeed improve the quality of the plugin, it is not the priority right now and we would rather work on other detectors.

Please let me know your thoughts,
_~tooryx_
