### ISSUE TITLE
AI PRP: GoCD Exposed UI

### ISSUE THREAD

**Issue by joernNNN** [google/tsunami-security-scanner-plugins#507]
Hello everyone,
I hope you're all doing well.

I'm excited that I'll be writing some new plugins for Google Tsunami! This is a great opportunity, and I can't wait to get started on this project. :))

Based on my preliminary research, GoCD doesn't have any authentication by default it is confirmed in two ways:
1. setup a [docker](https://hub.docker.com/r/gocd/gocd-server) instance: `docker run -d -p8153:8153 gocd/gocd-server:v24.1.0`
2. the first line of the docs is here: https://docs.gocd.org/current/configuration/dev_authentication.html

My thought is that this can be confirmed with of band call with the help of the tsunami callback server.

**Comment by tooryx** [comment]
Hey @joernNNN,

Thank you for willing to contribute. We are currently not interested in such a detector, but please continue to submit other ideas.

_~tooryx_

**Comment by tooryx** [comment]
Indeed, but we already have one implementation internally and we did not publish it yet.

_~tooryx_
