### ISSUE TITLE
PRP: Exposed code-server instance

### ISSUE THREAD

**Issue by joernNNN** [google/tsunami-security-scanner-plugins#508]
My second PRP:

In code server configuration password authentication can be disabled according to this part of the document:
https://coder.com/docs/code-server/guide#port-forwarding-via-ssh

Since this is an IDE, I believe, similar to GoCD, that the misconfiguration can be confirmed with the help of a Tsunami callback server.

**Comment by tooryx** [comment]
Hi @joernNNN,

We are not sure about this one yet. So could you start by writing a fingerprinting plugin for code-server?
If so, please open a new issue and I will accept it.

_~tooryx_
