### ISSUE TITLE
[Note]: Guys, looks like the project is INACTIVE

### ISSUE THREAD

**Issue by hayageek** [google/tsunami-security-scanner-plugins#513]
Hello everyone,

It appears that the project is inactive, with no responses from the team. I created a PR ([#488](https://github.com/google/tsunami-security-scanner-plugins/pull/488)) on May 21st, but have yet to receive any feedback.

**Please be advised:**
Don't waste your time working on this project.

**Comment by tooryx** [comment]
Hey @hayageek,

I am sorry that your experience with the review process has been so bad. Unfortunately, we are a very small team and if the project is definitely not inactive, it might take us some time to process PRs and issues.

Best regards,
_~tooryx_
