### ISSUE TITLE
PRP: Request Web Application Fingerprint - Confluence 

### ISSUE THREAD

**Issue by 0xtavi** [google/tsunami-security-scanner-plugins#64]
Hello,

I would like to start the implementation a for web application fingerprint that detects the following software - Confluence.

Docker hub image: https://hub.docker.com/r/atlassian/confluence

**Comment by maoning** [comment]
Hi @0xtavi ,

Thanks for your request! This vulnerability is in scope for the reward program. Please submit our [participation form](https://docs.google.com/forms/d/1SH8gyUnaGY3ezXY864oEuDZoOxrE5gJHYkcoiB_bu8I) and you can start working on the development.

Please keep in mind that the Tsunami Scanner Team will only be able to work at one issue at a time for each participant so please hold on the implementation work for any other requests you might have.

Thanks!

**Comment by 0xtavi** [comment]
Hello @maoning 

There's no example provided for web fingerprinters at https://github.com/google/tsunami-security-scanner-plugins/tree/master/examples . Also no community fingerprinter yet.

Should I add the fingerprinter for Confluence here https://github.com/google/tsunami-security-scanner-plugins/tree/master/google/fingerprinters/web ?

Thank you

**Comment by maoning** [comment]
@0xtavi That's correct! You can use https://github.com/google/tsunami-security-scanner-plugins/blob/master/google/fingerprinters/web/src/main/java/com/google/tsunami/plugins/fingerprinters/web/tools/FingerprintUpdater.java to generate the fingerprinting file for confluence.

**Comment by maoning** [comment]
You can use https://github.com/google/tsunami-security-scanner-plugins/commit/44945935781404f2de649bf6f88dd3d60acdae6b as an example for the automation script you need to implement to spin up different versions of the application to generate fingerprints.
