### ISSUE TITLE
Custom Nmap Report Parser does not accurately parse HTTP/HTTPS services

### ISSUE THREAD

**Issue by spaceraccoon** [google/tsunami-security-scanner-plugins#7]
The nmap plugin switched to a custom XML report parser from [this commit](https://github.com/google/tsunami-security-scanner-plugins/commit/10b1f90458307b5a347adae0cee941401080e43e). However, I noticed in certain cases where HTTPS was the actual service, nmap returned a result like this:

```
<service name="http" tunnel="ssl" method="probed" conf="10"/>
```

Even though the service name is `http`, the tunnel is `ssl`, so `https` would be a more appropriate tag. However, the parser simply takes the service name without further checks, causing requests to be sent to `http://<HOST>:443/`. Most servers reject such a request since SSL is required, leading to `unexpected end of stream` errors.

I've also noticed non-default HTTPS ports being wrongly interpreted as FTP or SSH. Perhaps the team could look into reverting back to the nmap plugin to parse results in the meantime while working on improving the XML parser.

**Comment by magl0** [comment]
This should be fixed by commit dda17ce053b599fa42090fea7169bc916d1f0b5a.
